/*
===============================================================================
Section:          Magnitude Analysis
===============================================================================
What this section does:   
This section breaks down the high-level KPIs into categorical buckets. By using 
GROUP BY and aggregate functions, it answers the "How much?" and "How many?" 
questions that drive business strategy.

Metrics analyzed here:
  - Customer Distribution: Grouping the customer base by Country and Gender to 
    identify key demographic segments.
  - Product Inventory: Counting the total number of products and calculating 
    the average cost within each product category.
  - Revenue & Volume Drivers: Joining the Fact table with Dimensions to uncover 
    which product categories generate the most revenue, which specific customers 
    are the top spenders, and which countries drive the highest sales volume.
===============================================================================
*/

-- find total customer by countries
SELECT country, COUNT(customer_key) total_customers
FROM g_dim_customer
GROUP BY  country
ORDER BY 2 DESC;

-- find total customer by gender
SELECT gender, COUNT(customer_key) total_customers
FROM g_dim_customer
GROUP BY  gender
ORDER BY 2 DESC;

-- find total product by category
SELECT category, COUNT(product_key) total_product
FROM g_dim_product
GROUP BY  category
ORDER BY 2 DESC;

-- what is the average cost in each category 
SELECT category, AVG(cost) avg_cost
FROM g_dim_product
GROUP BY category
ORDER BY 2 DESC;

-- what is total revenue generated by each category
SELECT p.category, SUM(s.price) total_revenue
FROM g_fact_sales s
LEFT JOIN g_dim_product p
	ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY 2 DESC;

-- find total revenue is generated by each costomer
SELECT c.customer_key,
c.first_name,
c.last_name,
SUM(s.price) total_revanue
FROM g_fact_sales s
LEFT JOIN g_dim_customer c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY 4 DESC;

-- what is the distribution of sold iteams across each country
SELECT c.country, SUM(quantity) total_quantity_sold
FROM g_fact_sales s
LEFT JOIN g_dim_customer c
	on s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 2 DESC;
